apiVersion: v1
kind: Service
metadata:
  name: {{ include "firstmate.fullname" . }}
  labels:
    {{- include "firstmate.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: walkie-talkie
      port: {{ .Values.service.port }}
      targetPort: walkie-talkie
      protocol: TCP
  selector:
    {{- include "firstmate.selectorLabels" . | nindent 4 }}
